server:
  # 项目端口
  port: 8080
  # url上下文前缀
  servlet:
    context-path: /
  # undertow 配置
  undertow:
    # 请求编码
    url-charset: utf-8
    # HTTP post内容的最大大小。当值为-1时，默认值为大小是无限的
    max-http-post-size: -1
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 512
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 8
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 256

# 日志配置
logging:
  level:
    com.mhd: debug
    org.springframework: warn
    org.mybatis.spring.mapper: error
  config: classpath:logback-spring.xml

spring:
  # 应用名
  application:
    name: mhd-push
  # 当前环境配置
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 开启文件上传
      enabled: true
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  mvc:
    # 设置静态资源路径 防止所有请求都去查静态资源
    static-path-pattern: /static/**
    # 请求时间格式化
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: dd/MM/yyyy
    pathmatch:
      # 旧项目可能使用 ant_path_matcher，建议使用 path_pattern_parser
      # 区别1：path_pattern_parser 性能比原先高，预先将路径模式编译为 PathPattern 对象，请求时直接复用编译结果，无需重复解析
      # 区别2：ant_path_matcher 对于末尾的/不区分，例如：/api/query与/api/query/都可以匹配，path_pattern_parser 严格区分
      matching-strategy: path_pattern_parser
  main:
    # 允许循环依赖
    # allow-circular-references: true
    # 关闭 banner
    banner-mode: off
  jackson:
    # 响应时间格式化
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区
    time-zone: GMT+8
    # 序列化配置（Java 对象 → JSON 字符串）
    serialization:
      # 关闭 JSON 格式化输出（紧凑格式）
      indent_output: false
      # 允许序列化空 Bean（无属性/无可序列化属性的对象）
      fail_on_empty_beans: false
    deserialization: # 反序列化配置（JSON 字符串 → Java 对象）
      # 忽略 JSON 中存在、Java 对象中不存在的属性
      fail_on_unknown_properties: false

# MybatisPLus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个 package 用逗号或者分号分隔
  typeAliasesPackage: com.mhd.push.**.entity
  configuration:
    # 自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    # 更详细的日志输出 会有性能损耗 org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭日志记录 (可单纯使用 p6spy 分析) org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 默认日志输出 org.apache.ibatis.logging.slf4j.Slf4jImpl
    logImpl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  #    cache-enabled: false # 关闭缓存
  #    call-setters-on-nulls: true # 若查询数据时字段值是 null 时，设置为 true 则显示当前字段名
  #    jdbc-type-for-null: 'null' # 插入数据时，如果有字段为空设置 null
  global-config:
    # 关闭启动LOGO
    banner: false
    db-config:
      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      id-type: auto
#      logic-delete-field: deleted # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
#      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0)

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: QSXRYJNF4510SDCC

nacos:
  config:
    server-addr: ${mhd.nacos.addr.ip:127.0.0.1}:${mhd.nacos.addr.port:8848}
    data-id: ${mhd.nacos.dataId:austin}
    group: ${mhd.nacos.group:DEFAULT_GROUP}

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: unique-producer-group

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true